---

- name: Converge
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  remote_user: root
  pre_tasks:
    - name: Ubuntu | Install python3
      ansible.builtin.raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)
      register: python3
      changed_when: "'installed' in python3.stdout"
      when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16)
    - name: RedHat | Install python3
      ansible.builtin.raw: test -e /usr/bin/python3 || (yum install -y python3)
      register: python3
      changed_when: "'installed' in python3.stdout"
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8)
    - name: Gather Facts
      ansible.builtin.setup:
      when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16)
    - name: Ubuntu Bionic+, Redhat 8+ | Enforce python3 for ansible
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/bin/python3
      when: >
        (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16) or
        (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8)
    - name: Extra daemons
      ansible.builtin.apt:
        name:
          - accountsservice
          - rsync
          - packagekit
          - policykit-1
          - avahi-daemon
          - bluetooth
          - wpasupplicant
          - modemmanager
          - iio-sensor-proxy
          - fwupd
          - openjdk-11-jdk
          - tomcat9
          - postgresql
        state: present
      register: pkg_result
      until: pkg_result is success
      when: ansible_distribution == "Ubuntu"
  vars:
    harden_systemd_list:
      - { t: accounts-daemon }
      - { t: dbus }
      - { t: rsync }
      - { t: packagekit }
      - { t: polkit }
      - { t: avahi-daemon }
      - { t: bluetooth }
      - { t: ModemManager }
      - { t: wpa_supplicant }
      - { t: rsyslog }
      - { t: iio-sensor-proxy }
      - { t: fwupd }
      - { t: walinuxagent }
      - { t: phpV-fpm, dstunit: php7.4-fpm }
      - { t: phpV-fpm, dstunit: php8.0-fpm }
      - { t: phpV-fpm, dstunit: php8.1-fpm }
      - { t: tomcat, dstunit: tomcat9 }
      - { t: postgresql, dstunit: postgresql@ }
  roles:
    - juju4.harden_systemd
