---

- name: Converge
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  remote_user: root
  pre_tasks:
    - name: Ubuntu | Install python3
      ansible.builtin.raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)
      register: python3
      changed_when: "'installed' in python3.stdout"
      when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16)
    - name: RedHat | Install python3
      ansible.builtin.raw: test -e /usr/bin/python3 || (yum install -y python3)
      register: python3
      changed_when: "'installed' in python3.stdout"
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8)
    - name: Gather Facts
      ansible.builtin.setup:
      when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16)
    - name: Ubuntu Bionic+, Redhat 8+ | Enforce python3 for ansible
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/bin/python3
      when: >
        (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16) or
        (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8)
    - name: apt | Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Extra daemons
      ansible.builtin.apt:
        name:
          - accountsservice
          - rsync
          - packagekit
          - policykit-1
          - avahi-daemon
          - bluetooth
          - wpasupplicant
          - modemmanager
          - iio-sensor-proxy
          - fwupd
          - openjdk-11-jdk
          - tomcat9
          - postgresql
          - omid
        state: present
      register: pkg_result
      until: pkg_result is success
      when: ansible_distribution == "Ubuntu"
    - name: Ubuntu Bionic | Set fact
      ansible.builtin.set_fact:
        harden_systemd_services_restart:
          - accounts-daemon
          - rsync
          - packagekit
          - polkit
          - avahi-daemon
          - bluetooth
          - ModemManager
          - wpa_supplicant
          - rsyslog
          - iio-sensor-proxy
          - fwupd
          - walinuxagent
          - php7.4-fpm
          - php8.0-fpm
          - php8.1-fpm
          - tomcat9
          - postgresql@10-main
          - omid
      when: >
        (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 18)
    - name: Download omsagent
      ansible.builtin.get_url:
        url: https://github.com/microsoft/OMS-Agent-for-Linux/releases/download/OMSAgent_v1.14.12-0/omsagent-1.14.12-0.universal.x64.sh
        dest: /tmp/omsagent.sh
        mode: '0755'
    - name: Install omsagent
      ansible.builtin.command: /tmp/omsagent.sh --install
      args:
        creates: /opt/microsoft/omsagent/bin/troubleshooter
  vars:
    harden_systemd_list:
      - { t: accounts-daemon }
      - { t: dbus }
      - { t: rsync }
      - { t: packagekit }
      - { t: polkit }
      - { t: avahi-daemon }
      - { t: bluetooth }
      - { t: ModemManager }
      - { t: wpa_supplicant }
      - { t: rsyslog }
      - { t: iio-sensor-proxy }
      - { t: fwupd }
      - { t: walinuxagent }
      - { t: phpV-fpm, dstunit: php7.4-fpm }
      - { t: phpV-fpm, dstunit: php8.0-fpm }
      - { t: phpV-fpm, dstunit: php8.1-fpm }
      - { t: tomcat, dstunit: tomcat9 }
      - { t: postgresql, dstunit: postgresql@ }
      - { t: omi, dstunit: omid }
      - { t: omsagent-GUID, dstunit: omsagent-GUID }
    harden_systemd_services_restart:
      - accounts-daemon
      # Failed to restart dbus.service: Operation refused, unit dbus.service may
      # be requested by dependency only (it is configured to refuse manual start/stop)
      # - dbus
      - rsync
      - packagekit
      - polkit
      - avahi-daemon
      - bluetooth
      - ModemManager
      - wpa_supplicant
      - rsyslog
      - iio-sensor-proxy
      - fwupd
      - walinuxagent
      - php7.4-fpm
      - php8.0-fpm
      - php8.1-fpm
      - tomcat9
      - postgresql@12-main
      - omid
  roles:
    - juju4.harden_systemd
