---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-ubuntu:20.04}
    # systemd support?
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    environment: { container: docker }
    # env:
    #   http_proxy: ${http_proxy}
    #   https_proxy: ${https_proxy}
    #   no_proxy: ${no_proxy}
    groups:
      - hardens
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 2
scenario:
  name: default
verifier:
  name: ansible
