---

- name: Verify
  hosts: hardens
  tasks:

    - name: Get /etc/systemd/system/rsyslog.service.d/hardening.conf stats
      ansible.builtin.stat:
        path: /etc/systemd/system/rsyslog.service.d/hardening.conf
      register: svc1
    - name: Validate /etc/systemd/system/rsyslog.service.d/hardening.conf exists
      ansible.builtin.assert:
        that: svc1.stat.exists and svc1.stat.size != 0

    - name: Debug | ansible_service_mgr
      ansible.builtin.debug: var=ansible_service_mgr verbosity=1

    - name: Get service status
      ansible.builtin.command: systemctl status rsyslog
      changed_when: false
      when: >
        ansible_service_mgr == 'systemd' and
        not (ansible_virtualization_type is defined and
              (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
            )
